name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Fixed the branch name to have a space after the dash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Python 3.10
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies from requirements.txt if it exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run unit tests
    - name: Run unit tests
      run: |
        python -m unittest test_calc.py  # Running tests using unittest
